name: Android CI (Debug)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Set up Gradle (non-wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Build Debug APK
        run: |
          gradle :app:assembleDebug
          # ทำสำเนาชื่อไฟล์ให้ตรงกับปุ่ม README เดิม
          cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-release.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ForceWipeApp-debug-apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0-debug-${{ github.run_number }}
          name: Debug ${{ github.run_number }}
          body: Automated debug build.
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
